use_frameworks!

platform :ios, '9.0'

target 'XXYUIKitExtension_Example' do
  #pod 'XXYUIKitExtension', :path => '../'
  
  pod 'XXYUIKitExtension', :podspec => '../XXYUIKitExtension.podspec'
  target 'XXYUIKitExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
